// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonNotebook: typeof import('~icons/carbon/notebook')['default']
    HeaderPage: typeof import('./src/components/HeaderPage.vue')['default']
    LogoIcons: typeof import('./src/components/LogoIcons.vue')['default']
  }
}
